name: mallm
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.12
  - fire
  - tqdm
  - langchain-core
  - langchain
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - transformers
  - accelerate
  - nltk
  - rouge_score
  - bert_score
  - pip
  - pip:
      - -e .
      - bitsandbytes
